---
type: pipeline
name: Build Reeve Step "SSH"

when:
  workerGroup:
    include: [soldier]
  trigger:
    include: [commit, action]
  file:
    include:
      - .env
      - .reeve.yaml
  action:
    include: [reeveci:steps:ssh:build]

steps:
  - name: Load env
    task: "@reeve/load-env-file"
    params:
      LOAD_ALL: "true"

  - name: Build image
    task: "@docker/build"
    params:
      DOCKER_LOGIN_REGISTRY: docker.io
      DOCKER_LOGIN_USER: { env: docker/github/user }
      DOCKER_LOGIN_PASSWORD: { env: docker/github/password }
      NAME: docker.io/reeveci/step-ssh
      TAG: { var: STEP_VERSION }
      PLATFORM: amd64
